feat: remove from Staff
bcneng/website pull request #93
Opened 2022-01-09 19:25 UTC by smoya

Our friend @KoeSystems is not part of the staff anymore, unfortunately. However, we appreciate all this time with us. He helped **a lot** to BCN Eng and tons of things it wouldn't be possible without his help.

Luckily Koe is still on slack! ❤️

2022-01-09 19:49 UTC, gonzaloserrano approved these changes

2022-01-10 06:58 UTC, sdecandelario requested changes

2022-01-10 06:58 UTC, sdecandelario commented on content/about.md
> -[{{< figure src="/images/team/koe.png" title="@koe" class="avatar" >}}](https://bcneng.slack.com/team/U7PQZMZ4L)
También habría que borrar la foto de `static/images/team/`

2022-01-10 11:24 UTC, smoya commented on content/about.md
> -[{{< figure src="/images/team/koe.png" title="@koe" class="avatar" >}}](https://bcneng.slack.com/team/U7PQZMZ4L)
Done!

2022-01-10 11:34 UTC, merged